### ISSUE TITLE
Questions about the size of the .elf files and build time.

### ISSUE THREAD

**Issue by lishen565** [Xilinx/CHaiDNN#14]
Hi all, I've test the example elf in our project and they work well. Then I had builded the project in SDx GUI and found that the elf was about 10MB. But the example elf in CHaiDNN project is about 59kB. Why my elf file which produced by SDx is much larger than yours?
The six example elf you provided could work well on the same FPGA bitstream. So I think the example elf  has few relationship about the bitstream. I don't want to rebuild the whole project just as I  modified the application code, because it would take a very long time to complete the build procedure. Do you have any good way to shorten the rebuild time?
Thanks a lot!

**Comment by NeutrinoXY** [comment]
Hello,

When you build your project, you can choose to create a library file instead of creating a single elf for your application. Thus, you can compile your application separately, and it takes a few seconds. This is how the provided .elf examples have been built.

You can choose this option in SDx GUI, or you can use the provided makefile.

Best regards.

**Comment by lishen565** [comment]
Thanks a lot. I'll try that as your advice.

**Comment by VishalX** [comment]
Closing this issue.
