### ISSUE TITLE
Abnormal execution time

### ISSUE THREAD

**Issue by NeutrinoXY** [Xilinx/CHaiDNN#76]
Hi,

I'm running a simple Cifar-10 classifier. However, I get an abnormal execution time for the third pooling layer : 1.5 ms for an average pooling. I also tried with a max pooling and it's worse : 1.9 ms.

I also ran the network using the ARM processor only (no functions on the PL), and the execution times are not surprising (the third pool now takes less time than the second, which is logical).

I inserted all the needed files (prototxt, weights, layerwise_latency logs) in the attached archive : 
[execution_time_issue.zip](https://github.com/Xilinx/CHaiDNN/files/2483000/execution_time_issue.zip)

Any help would be appreciated.

Thanks.

Neutrino

**Comment by VishalX** [comment]
@NeutrinoXY,

Could you share some more details on the design configs, device used, etc. 
Also, please try to use Eval API to cross-check your performance numbers.

**Comment by VishalX** [comment]
@NeutrinoXY,

These are very good observations.

Yes, It is because of how the memory is allocated. But not because of bad offsets. 
Hardware accelerators work well with non-cacheable memory. What I meant to say is, if you have allocated both input and output buffers with `sds_alloc_non_cacheable`, the latencies would be fine, else the performance goes down a little. 

For a large network, this performance decay on one layer might not affect the overall performance of the network. But in smaller networks or networks with less computes, it might affects significantly. And I think, that's what you're also observing.

In CIFAR-10, the layer after `pool3` is `ip1` (FC layer), for which we need to re-arrange the o/p of pooling layer before feeding it to inner product layer. The memory used for the o/p of `pool3` is most probably allocated by buffer management as `cacheable`, hence the impact on performance.

Let me know if you've seen performance impact on any other networks too.

Thanks!
